import type { TCourse } from '@http/courses/type'

export const courseMockData: TCourse[] = [
  {
    id: 'asdasd#1',
    title: 'Тестовий курс',
    description: 'Тестовий курс',
    start_date: '2020-01-01',
    categories_repr: ['Тестовий курс', 'IT'],
    price: 1100,
    discount: 1099,
    rating: 3.8,
    color: '',
    cover: 'https://loremflickr.com/640/360',
    format: 'live',
    purchased: false,
    lectors: [
      {
        id: 'asdasd#1',
        first_name: 'ВасилІй',
        last_name: 'Іванов',
        patronymic: 'Іванович',
        avatar: 'https://loremflickr.com/640/360',
      },
    ],
    number_of_lectures: 101,
    max_number_of_students: 0,
    number_of_students: 0,
  },
  {
    id: 'asdasd#2',
    title: 'Тестовий курс 2',
    description: 'Тестовий курс',
    start_date: '2020-01-01',
    categories_repr: ['Тестовий курс', 'IT'],
    price: 0,
    discount: 0,
    rating: 3.8,
    color: 'pink',
    cover: 'https://loremflickr.com/640/360',
    format: 'live',
    purchased: true,
    lectors: [
      {
        id: 'asdasd#1',
        first_name: 'ВасилІй',
        last_name: 'Іванов',
        patronymic: 'Іванович',
        avatar: 'https://loremflickr.com/640/360',
      },
    ],
    number_of_lectures: 101,
    max_number_of_students: 10,
    number_of_students: 9,
  },
  {
    id: 'asdasd#3',
    title: 'Тестовий курс 3. Поглиблене вивчення',
    description: 'Тестовий курс',
    start_date: '2020-01-01',
    categories_repr: ['Тестовий курс', 'IT'],
    price: 9991,
    discount: 0,
    rating: 3.8,
    color: '#fff8ed',
    cover: 'https://loremflickr.com/640/360',
    format: 'live',
    purchased: false,
    lectors: [
      {
        id: 'asdasd#1',
        first_name: 'Василій',
        last_name: 'Іванов',
        patronymic: 'Іванович',
        avatar: 'https://loremflickr.com/640/360',
      },
      {
        id: 'asdasd#2',
        first_name: 'Василіса',
        last_name: 'Іванова',
        patronymic: 'Іванівна',
        avatar: 'https://loremflickr.com/640/360',
      },
    ],
    number_of_lectures: 101,
    max_number_of_students: 10,
    number_of_students: 9,
  },
]
